### ISSUE TITLE
UI: rearrange items in the city production worklist

### ISSUE THREAD

**Issue by kvilhaugsvik** [freeciv/freeciv-web#77] opened 2017-05-29 13:41 UTC
Allow items in a city's production worklist to be rearranged.

See the TODO file for more information about this feature and how it can be implemented in freeciv-web.

**Comment by lonemadmax** [comment] 2017-07-15 11:49
Am I missing something or is this a duplicate of #21?

**Closed as completed** 2017-07-18 19:10 UTC

**Comment by ghost** [comment] 2017-07-18 19:15
Awesome!
