### ISSUE TITLE
Unable to start ?

### ISSUE THREAD

**Issue by Scratchmang** [freeciv/freeciv-web#294] opened 2019-12-02 21:13 UTC
So,

First time user of Freeciv-web. Downloaded the code, Vagrant, Virtual box as per the documentation on a clean fresh install of Ubuntu 18 LTS....

Everything seems to have installed as it should, no errors or issues. When I do 'vagrant ssh' I connect, all well and good.

I can point my Web Browser to the Host Machine and I get the "Welcome Page" but form there, nothing. Cannot start a game (Single or MultiPlayer) Just sits there...

I assume I'm missing something here, I've look and searched by cannot find anything as to where or what I may be doing wrong. Any help or suggestions would be appreciated.

**Comment by andreasrosdalw** [comment] 2019-12-04 09:51
Hello! Possible duplicate of #293 ?

**Comment by Scratchmang** [comment] 2019-12-04 14:36
Possibly?

I'm running the Vagrant/VirtualBox version. so that might be it. Let me do some digging.

**Comment by andreasrosdalw** [comment] 2019-12-05 20:47
duplicate

**Closed as completed by andreasrosdalw** 2019-12-05 20:47 UTC
